title: Welcome To My Little Section Of The Internet
description: > # this means to ignore newlines until "baseurl:"
  Personal website for Abdurrahman Dridi, keep updated here!
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Abdul Dridi # add your name
author-img:  myCat.jpg # add your photo
about-author: A computer science student at the University of Manchester. Interested in NLP & machine learning, lifting weights and reading books! # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-goodreads: 77881457-abdurrahman-dridi # add your GoodReads handle
social-github: AbdulDridi # add your Github handle
social-linkedin: abdurrahman-dridi-0203aa12a # add your Linkedin handle
social-email: abdurrahmandridi@gmail.com # add your Email address
cv-file: AbdurrahmanDridiCV.pdf # add your cv/resume file

# Disqus
discus-identifier:  abdurrahmandridi # add your discus identifier

# Tracker
analytics: UA-125413493-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
